name: Deploy to Firebase 

on: 
  push: 
    branches: 
      - main 

jobs: 
  deploy: 
    runs-on: ubuntu-latest 

    steps: 
      - name: Checkout repository 
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'latest'
  
      - name: Install dependencies
        run: npm install
  
      - name: Build React app
        run: npm run build
  
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
  
      - name: Authenticate Firebase
        run: firebase login:ci --token "$FIREBASE_TOKEN"
  
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting